/*
Navicat MySQL Data Transfer

Source Server         : new
Source Server Version : 50561
Source Host           : localhost:3306
Source Database       : tjxf2

Target Server Type    : MYSQL
Target Server Version : 50561
File Encoding         : 65001

Date: 2020-06-19 11:28:39
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for a11_baseinfo
-- ----------------------------
DROP TABLE IF EXISTS `a11_baseinfo`;
CREATE TABLE `a11_baseinfo` (
  `Acc_ID` int(11) NOT NULL DEFAULT '0' COMMENT '事故ID',
  `Time_Find` datetime DEFAULT NULL COMMENT '发现或报警时间',
  `Car_Num` int(4) DEFAULT NULL COMMENT '涉及车辆数',
  `Hurt_Num` int(4) DEFAULT NULL COMMENT '伤亡人数',
  `Loc_Sheng` varchar(10) DEFAULT NULL COMMENT '地点 省',
  `Loc_Shi` varchar(20) DEFAULT NULL,
  `Loc_Xian` varchar(20) DEFAULT NULL,
  `Loc_Detail` varchar(50) DEFAULT NULL,
  `People_Num` int(4) DEFAULT NULL COMMENT '所有涉案车辆的人数',
  `Gov_CJ` varchar(20) DEFAULT NULL COMMENT '采集人',
  `Gov_LR` varchar(20) DEFAULT NULL COMMENT '录入人',
  `Time_Police` datetime DEFAULT NULL,
  `Time_Invest` datetime DEFAULT NULL COMMENT '调查时间',
  `Fire_Tru` varchar(10) DEFAULT NULL COMMENT '消防车是否到场',
  `Time_FireTru` datetime DEFAULT NULL,
  `Ambulance` varchar(10) DEFAULT NULL COMMENT '救护车是否到场',
  `Time_Ambu` datetime DEFAULT NULL,
  `State` varchar(20) DEFAULT NULL COMMENT '现场形态',
  `Status` int(4) DEFAULT NULL,
  `id` int(11) NOT NULL COMMENT '用户ID',
  `Time_Insert` datetime DEFAULT NULL COMMENT '插入数据库时间',
  PRIMARY KEY (`Acc_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for a12_envinfo
-- ----------------------------
DROP TABLE IF EXISTS `a12_envinfo`;
CREATE TABLE `a12_envinfo` (
  `Acc_ID` int(11) NOT NULL,
  `Location` varchar(20) DEFAULT NULL COMMENT '事故地点',
  `RoadInfo_CT` varchar(20) DEFAULT NULL COMMENT '沿着车头的趋势',
  `RoadInfo_PD` int(11) DEFAULT NULL COMMENT '车头坡度',
  `RoadInfo_CZ` varchar(20) DEFAULT NULL COMMENT '道路状况表面材质',
  `RoadInfo_ZK` varchar(20) DEFAULT NULL COMMENT '道路信息表面状况',
  `RoadInfo_JK` varchar(20) DEFAULT NULL COMMENT '道路信息周围监控',
  `WeaInfo_TQ` varchar(20) DEFAULT NULL COMMENT '气象信息天气',
  `WeaInfo_FX` varchar(20) DEFAULT NULL COMMENT '气象信息风向',
  `WeaInfo_FL` varchar(20) DEFAULT NULL COMMENT '气象信息风力',
  `WeaInfo_WD` int(11) DEFAULT NULL COMMENT '气象信息温度',
  `Protect_XC` varchar(20) DEFAULT NULL COMMENT '现场有无保护',
  `Protect_CL` varchar(20) DEFAULT NULL COMMENT '车辆有无保护',
  `WeaInfo_FS` int(11) DEFAULT NULL,
  PRIMARY KEY (`Acc_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b1_innerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b1_innerinfo`;
CREATE TABLE `b1_innerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL COMMENT '事故编码',
  `VIN` varchar(255) DEFAULT NULL,
  `Barry_Pos` varchar(25) DEFAULT NULL COMMENT '蓄电池位置',
  `Barry_Vol` varchar(25) DEFAULT NULL COMMENT '蓄电池电压',
  `Barry_Break_Degree` varchar(25) DEFAULT NULL COMMENT '蓄电池烧损程度',
  `OilTank_Pos` varchar(25) DEFAULT NULL COMMENT '油箱加油口位置',
  `OilTank_Material` varchar(25) DEFAULT NULL COMMENT '油箱材料',
  `OilTank_Vol` varchar(25) DEFAULT NULL COMMENT '油箱油量',
  `OilTank_Break_Degree` varchar(25) DEFAULT NULL COMMENT '油箱烧损程度',
  `FDJC_FDongJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发动机',
  `FDJC_JQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱进气歧管',
  `FDJC_FDianJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发电机',
  `FDJC_PQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱排气歧管',
  `FDJC_QDJ` varchar(25) DEFAULT NULL COMMENT '发动机舱起动机',
  `FDJC_WLZYQ` varchar(25) DEFAULT NULL COMMENT '发动机舱涡轮增压器',
  `FDJC_DHXQ` varchar(25) DEFAULT NULL COMMENT '发动机舱点火线圈',
  `FDJC_LQYG` varchar(25) DEFAULT NULL COMMENT '发动机舱冷却液罐',
  `FDJC_JYLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱机油滤清器',
  `FDJC_QXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱清洗液罐',
  `FDJC_KQLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱空气滤清器',
  `FDJC_ZDYG` varchar(25) DEFAULT NULL COMMENT '发动机舱制动液罐',
  `FDJC_ZKZLQ` varchar(25) DEFAULT NULL COMMENT '发动机舱真空助力器',
  `FDJC_ZLZXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱助力转向液罐',
  `FDJC_BXH` varchar(25) DEFAULT NULL COMMENT '发动机舱保险盒',
  `FDJC_KTYSJ` varchar(25) DEFAULT NULL COMMENT '发动机舱空调压缩机',
  `FDJC_BSQ_LHQ` varchar(25) DEFAULT NULL COMMENT '发动机舱变速器离合器',
  `FDJC_ABS` varchar(25) DEFAULT NULL COMMENT '发动机舱ABS控制器',
  `FDJC_SRQ` varchar(25) DEFAULT NULL COMMENT '发动机舱散热器',
  `FDJC_ZQD` varchar(25) DEFAULT NULL COMMENT '发动机舱左前灯',
  `FDJC_LNQ` varchar(25) DEFAULT NULL COMMENT '发动机舱冷凝器',
  `FDJC_YQD` varchar(25) DEFAULT NULL COMMENT '发动机舱右前灯',
  `FDJC_LQFS` varchar(25) DEFAULT NULL COMMENT '发动机舱冷却风扇',
  `JSS_YBB` varchar(25) DEFAULT NULL COMMENT '驾驶室仪表板',
  `JSS_DYQ` varchar(25) DEFAULT NULL COMMENT '驾驶室点烟器',
  `JSS_ZXP` varchar(25) DEFAULT NULL COMMENT '驾驶室转向盘',
  `JSS_STX` varchar(25) DEFAULT NULL COMMENT '驾驶室手套箱',
  `JSS_ZYJXH` varchar(25) DEFAULT NULL COMMENT '驾驶室中央接线盒',
  `JSS_ZYFSX` varchar(25) DEFAULT NULL COMMENT '驾驶室中央扶手箱',
  `JSS_DHKG` varchar(25) DEFAULT NULL COMMENT '驾驶室点火开关',
  `JSS_JSWZY` varchar(25) DEFAULT NULL COMMENT '驾驶室驾驶位坐椅',
  `JSS_BFQ` varchar(25) DEFAULT NULL COMMENT '驾驶室播放器',
  `JSS_FJSZY` varchar(25) DEFAULT NULL COMMENT '驾驶室副驾驶座椅',
  `JSS_GFJ` varchar(25) DEFAULT NULL COMMENT '驾驶室 鼓风机',
  `JSS_HPZY` varchar(25) DEFAULT NULL COMMENT '驾驶室后排座椅',
  `JSS_ZQM` varchar(25) DEFAULT NULL COMMENT '驾驶室左前门',
  `JSS_YQM` varchar(25) DEFAULT NULL COMMENT '驾驶室右前门',
  `JSS_ZHM` varchar(25) DEFAULT NULL COMMENT '驾驶室左后门',
  `JSS_YHM` varchar(25) DEFAULT NULL COMMENT '驾驶室右后门',
  `HBX_ZHCD` varchar(25) DEFAULT NULL COMMENT '后备箱左后车灯',
  `HBX_YHCD` varchar(25) DEFAULT NULL COMMENT '后备箱右后车灯',
  `HBX_BT` varchar(25) DEFAULT NULL COMMENT '后备箱备胎',
  `HBX_Object1` varchar(25) DEFAULT NULL COMMENT '后备箱主要物品1',
  `Object1_BurnDegree` varchar(25) DEFAULT NULL COMMENT '主要物品1烧损程度',
  `HBX_Object2` varchar(25) DEFAULT NULL COMMENT '后备箱主要物品2',
  `Object2_BurnDegree` varchar(25) DEFAULT NULL COMMENT '主要物品2 烧损程度',
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b1_outerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b1_outerinfo`;
CREATE TABLE `b1_outerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(255) DEFAULT NULL,
  `LT_ZQ` varchar(25) DEFAULT NULL,
  `LT_YQ` varchar(25) DEFAULT NULL,
  `LT_ZH` varchar(25) DEFAULT NULL,
  `LT_YH` varchar(25) DEFAULT NULL,
  `LW_ZQ` varchar(25) DEFAULT NULL,
  `LW_YQ` varchar(25) DEFAULT NULL,
  `LW_ZH` varchar(25) DEFAULT NULL,
  `LW_YH` varchar(25) DEFAULT NULL,
  `CM_ZQ` varchar(25) DEFAULT NULL,
  `CM_YQ` varchar(25) DEFAULT NULL,
  `CM_ZH` varchar(25) DEFAULT NULL,
  `CM_YH` varchar(25) DEFAULT NULL,
  `CC_ZQ` varchar(25) DEFAULT NULL,
  `CC_YQ` varchar(25) DEFAULT NULL,
  `CC_ZH` varchar(25) DEFAULT NULL,
  `CC_YH` varchar(25) DEFAULT NULL,
  `YZB_ZQ` varchar(25) DEFAULT NULL,
  `YZB_YQ` varchar(25) DEFAULT NULL,
  `YZB_ZH` varchar(25) DEFAULT NULL,
  `YZB_YH` varchar(25) DEFAULT NULL,
  `CD_ZQ` varchar(25) DEFAULT NULL,
  `CD_YQ` varchar(25) DEFAULT NULL,
  `CD_ZH` varchar(25) DEFAULT NULL,
  `CD_YH` varchar(25) DEFAULT NULL,
  `HSJ_ZQ` varchar(25) DEFAULT NULL,
  `HSJ_YQ` varchar(25) DEFAULT NULL,
  `BXG_QB` varchar(25) DEFAULT NULL,
  `BXG_HB` varchar(25) DEFAULT NULL,
  `FDBO_QB` varchar(25) DEFAULT NULL,
  `FDBL_HB` varchar(25) DEFAULT NULL,
  `YGQ_QB` varchar(25) DEFAULT NULL,
  `YGQ_HB` varchar(25) DEFAULT NULL,
  `FDJCG` varchar(25) DEFAULT NULL,
  `DG` varchar(25) DEFAULT NULL,
  `TC` varchar(25) DEFAULT NULL,
  `HBXG` varchar(25) DEFAULT NULL,
  `DP` varchar(25) DEFAULT NULL,
  `PQG` varchar(25) DEFAULT NULL,
  `CHZHQ` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=304 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b2_innerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b2_innerinfo`;
CREATE TABLE `b2_innerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL COMMENT '事故编码',
  `VIN` varchar(255) DEFAULT NULL,
  `XDC_WZ` varchar(25) DEFAULT NULL,
  `XDC_DY` varchar(25) DEFAULT NULL,
  `XDC_SSCD` varchar(25) DEFAULT NULL,
  `OilTank_Pos` varchar(25) DEFAULT NULL COMMENT '油箱加油口位置',
  `OilTank_Material` varchar(25) DEFAULT NULL COMMENT '油箱材料',
  `OilTank_Vol` varchar(25) DEFAULT NULL COMMENT '油箱油量',
  `OilTank_Break_Degree` varchar(25) DEFAULT NULL COMMENT '油箱烧损程度',
  `FDJC_FDongJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发动机',
  `FDJC_JQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱进气歧管',
  `FDJC_FDianJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发电机',
  `FDJC_PQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱排气歧管',
  `FDJC_QDJ` varchar(25) DEFAULT NULL COMMENT '发动机舱起动机',
  `FDJC_WLZYQ` varchar(25) DEFAULT NULL COMMENT '发动机舱涡轮增压器',
  `FDJC_CYB` varchar(25) DEFAULT NULL,
  `FDJC_LQYG` varchar(25) DEFAULT NULL,
  `FDJC_DHXQ` varchar(25) DEFAULT NULL COMMENT '发动机舱点火线圈',
  `FDJC_QXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱清洗液罐',
  `FDJC_JYLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱机油滤清器',
  `FDJC_ZDYG` varchar(25) DEFAULT NULL,
  `FDJC_KQLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱空气滤清器',
  `FDJC_ZLZXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱助力转向液罐',
  `FDJC_ZKZLQ` varchar(25) DEFAULT NULL COMMENT '发动机舱真空助力器',
  `FDJC_KTYSJ` varchar(25) DEFAULT NULL COMMENT '发动机舱空调压缩机',
  `FDJC_BXH` varchar(25) DEFAULT NULL COMMENT '发动机舱保险盒',
  `FDJC_ABS` varchar(25) DEFAULT NULL COMMENT '发动机舱ABS控制器',
  `FDJC_BSQ_LHQ` varchar(25) DEFAULT NULL COMMENT '发动机舱变速器离合器',
  `FDJC_ZQD` varchar(25) DEFAULT NULL COMMENT '发动机舱左前灯',
  `FDJC_SRQ` varchar(25) DEFAULT NULL COMMENT '发动机舱散热器',
  `FDJC_YQD` varchar(25) DEFAULT NULL COMMENT '发动机舱右前灯',
  `FDJC_LNQ` varchar(25) DEFAULT NULL COMMENT '发动机舱冷凝器',
  `FDJC_LQFS` varchar(25) DEFAULT NULL COMMENT '发动机舱冷却风扇',
  `JSS_YBB` varchar(25) DEFAULT NULL COMMENT '驾驶室仪表板',
  `JSS_JXH` varchar(25) DEFAULT NULL,
  `JSS_ZXP` varchar(25) DEFAULT NULL COMMENT '驾驶室转向盘',
  `JSS_STX` varchar(25) DEFAULT NULL COMMENT '驾驶室手套箱',
  `JSS_GFJ` varchar(25) DEFAULT NULL COMMENT '驾驶室 鼓风机',
  `JSS_JSWZY` varchar(25) DEFAULT NULL COMMENT '驾驶室驾驶位坐椅',
  `JSS_BFQ` varchar(25) DEFAULT NULL COMMENT '驾驶室播放器',
  `JSS_FJSZY` varchar(25) DEFAULT NULL COMMENT '驾驶室副驾驶座椅',
  `JSS_DYQ` varchar(25) DEFAULT NULL COMMENT '驾驶室点烟器',
  `JSS_HPZY` varchar(25) DEFAULT NULL COMMENT '驾驶室后排座椅',
  `JSS_ZQD` varchar(25) DEFAULT NULL,
  `JSS_YQD` varchar(25) DEFAULT NULL,
  `JSS_ZQM` varchar(25) DEFAULT NULL COMMENT '驾驶室左前门',
  `JSS_YQM` varchar(25) DEFAULT NULL COMMENT '驾驶室右前门',
  `JSS_ZHM` varchar(25) DEFAULT NULL COMMENT '驾驶室左后门',
  `JSS_YHM` varchar(25) DEFAULT NULL COMMENT '驾驶室右后门',
  `CX_QBZC` varchar(25) DEFAULT NULL,
  `CX_HBZC` varchar(25) DEFAULT NULL,
  `CX_ZBBZC` varchar(25) DEFAULT NULL,
  `CX_YBBZC` varchar(25) DEFAULT NULL,
  `CX_DBZC` varchar(25) DEFAULT NULL,
  `CX_DB` varchar(25) DEFAULT NULL,
  `CX_ZHCD` varchar(25) DEFAULT NULL,
  `CX_YHCD` varchar(25) DEFAULT NULL,
  `CX_ZYWP` varchar(25) DEFAULT NULL,
  `CX_SSCD` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b2_outerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b2_outerinfo`;
CREATE TABLE `b2_outerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(25) DEFAULT NULL,
  `LT_Z1` varchar(25) DEFAULT NULL,
  `LT_Z2` varchar(25) DEFAULT NULL,
  `LT_Z3` varchar(25) DEFAULT NULL,
  `LT_Z4` varchar(25) DEFAULT NULL,
  `LT_Y1` varchar(25) DEFAULT NULL,
  `LT_Y2` varchar(25) DEFAULT NULL,
  `LT_Y3` varchar(25) DEFAULT NULL,
  `LT_Y4` varchar(25) DEFAULT NULL,
  `LW_Z1` varchar(25) DEFAULT NULL,
  `LW_Z2` varchar(25) DEFAULT NULL,
  `LW_Z3` varchar(25) DEFAULT NULL,
  `LW_Z4` varchar(25) DEFAULT NULL,
  `LW_Y1` varchar(25) DEFAULT NULL,
  `LW_Y2` varchar(25) DEFAULT NULL,
  `LW_Y3` varchar(25) DEFAULT NULL,
  `LW_Y4` varchar(25) DEFAULT NULL,
  `CM_Z1` varchar(25) DEFAULT NULL,
  `CM_Z2` varchar(25) DEFAULT NULL,
  `CM_Y1` varchar(25) DEFAULT NULL,
  `CM_Y2` varchar(25) DEFAULT NULL,
  `CC_Z1` varchar(25) DEFAULT NULL,
  `CC_Z2` varchar(25) DEFAULT NULL,
  `CC_Y1` varchar(25) DEFAULT NULL,
  `CC_Y2` varchar(25) DEFAULT NULL,
  `YZB_Z` varchar(25) DEFAULT NULL,
  `YZB_Y` varchar(25) DEFAULT NULL,
  `CD_Z1` varchar(25) DEFAULT NULL,
  `CD_Z2` varchar(25) DEFAULT NULL,
  `CD_Z3` varchar(25) DEFAULT NULL,
  `CD_Z4` varchar(25) DEFAULT NULL,
  `CD_Y1` varchar(25) DEFAULT NULL,
  `CD_Y2` varchar(25) DEFAULT NULL,
  `CD_Y3` varchar(25) DEFAULT NULL,
  `CD_Y4` varchar(25) DEFAULT NULL,
  `HSJ_Z` varchar(25) DEFAULT NULL,
  `HSJ_Y` varchar(25) DEFAULT NULL,
  `BXG_QB` varchar(25) DEFAULT NULL,
  `BXG_HB` varchar(25) DEFAULT NULL,
  `FDBL_QB` varchar(25) DEFAULT NULL,
  `FDBL_HB` varchar(25) DEFAULT NULL,
  `YGQ_QB` varchar(25) DEFAULT NULL,
  `PZSX` varchar(25) DEFAULT NULL,
  `JSSDG` varchar(25) DEFAULT NULL,
  `JSSHWB` varchar(25) DEFAULT NULL,
  `QBZC` varchar(25) DEFAULT NULL,
  `HBZC` varchar(25) DEFAULT NULL,
  `ZBBZC` varchar(25) DEFAULT NULL,
  `DBZC` varchar(25) DEFAULT NULL,
  `YBBZC` varchar(25) DEFAULT NULL,
  `DB` varchar(25) DEFAULT NULL,
  `DP` varchar(25) DEFAULT NULL,
  `BT` varchar(25) DEFAULT NULL,
  `PQG` varchar(25) DEFAULT NULL,
  `CHZHQ` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b3_innerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b3_innerinfo`;
CREATE TABLE `b3_innerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL COMMENT '事故编码',
  `VIN` varchar(255) DEFAULT NULL,
  `XDC_WZ` varchar(25) DEFAULT NULL,
  `XDC_DY` varchar(25) DEFAULT NULL,
  `XDC_SSCD` varchar(25) DEFAULT NULL,
  `OilTank_Pos` varchar(25) DEFAULT NULL COMMENT '油箱加油口位置',
  `OilTank_Material` varchar(25) DEFAULT NULL COMMENT '油箱材料',
  `OilTank_Vol` varchar(25) DEFAULT NULL COMMENT '油箱油量',
  `OilTank_Break_Degree` varchar(25) DEFAULT NULL COMMENT '油箱烧损程度',
  `FDJC_FDongJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发动机',
  `FDJC_JQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱进气歧管',
  `FDJC_FDianJ` varchar(25) DEFAULT NULL COMMENT '发动机舱发电机',
  `FDJC_PQQG` varchar(25) DEFAULT NULL COMMENT '发动机舱排气歧管',
  `FDJC_QDJ` varchar(25) DEFAULT NULL COMMENT '发动机舱起动机',
  `FDJC_WLZYQ` varchar(25) DEFAULT NULL COMMENT '发动机舱涡轮增压器',
  `FDJC_CYB` varchar(25) DEFAULT NULL,
  `FDJC_LQYG` varchar(25) DEFAULT NULL,
  `FDJC_HSQ` varchar(25) DEFAULT NULL,
  `FDJC_QXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱清洗液罐',
  `FDJC_DHXQ` varchar(25) DEFAULT NULL COMMENT '发动机舱点火线圈',
  `FDJC_ZDYG` varchar(25) DEFAULT NULL,
  `FDJC_KQLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱空气滤清器',
  `FDJC_ZLZXYG` varchar(25) DEFAULT NULL COMMENT '发动机舱助力转向液罐',
  `FDJC_JYLQQ` varchar(25) DEFAULT NULL COMMENT '发动机舱机油滤清器',
  `FDJC_KTYSJ` varchar(25) DEFAULT NULL COMMENT '发动机舱空调压缩机',
  `FDJC_ZKZLQ` varchar(25) DEFAULT NULL COMMENT '发动机舱真空助力器',
  `FDJC_ABS` varchar(25) DEFAULT NULL COMMENT '发动机舱ABS控制器',
  `FDJC_BXH` varchar(25) DEFAULT NULL COMMENT '发动机舱保险盒',
  `FDJC_KQYSJ` varchar(25) DEFAULT NULL,
  `FDJC_BSQ_LHQ` varchar(25) DEFAULT NULL COMMENT '发动机舱变速器离合器',
  `FDJC_LQFS` varchar(25) DEFAULT NULL COMMENT '发动机舱冷却风扇',
  `FDJC_SRQ` varchar(25) DEFAULT NULL COMMENT '发动机舱散热器',
  `FDJC_DYZKG` varchar(25) DEFAULT NULL,
  `FDJC_LNQ` varchar(25) DEFAULT NULL COMMENT '发动机舱冷凝器',
  `FDJC_JXH` varchar(25) DEFAULT NULL,
  `CYC_YBB` varchar(25) DEFAULT NULL,
  `CYC_BFQ` varchar(25) DEFAULT NULL,
  `CYC_JXH` varchar(25) DEFAULT NULL,
  `CYC_JSQ` varchar(25) DEFAULT NULL,
  `CYC_ZXP` varchar(25) DEFAULT NULL,
  `CYC_JSWZY` varchar(25) DEFAULT NULL,
  `CYC_DHKG` varchar(25) DEFAULT NULL,
  `CYC_FJSZQ` varchar(25) DEFAULT NULL,
  `CYC_GFJ` varchar(25) DEFAULT NULL,
  `CYC_CKZY` varchar(25) DEFAULT NULL,
  `CYC_QBDB` varchar(25) DEFAULT NULL,
  `CYC_HBDB` varchar(25) DEFAULT NULL,
  `CYC_ZQCD` varchar(25) DEFAULT NULL,
  `CYC_YQZD` varchar(25) DEFAULT NULL,
  `CYC_ZHCD` varchar(25) DEFAULT NULL,
  `CYC_YHCD` varchar(25) DEFAULT NULL,
  `CYC_Z1` varchar(25) DEFAULT NULL,
  `CYC_Y1` varchar(25) DEFAULT NULL,
  `CYC_Y2` varchar(25) DEFAULT NULL,
  `CYC_Y3` varchar(25) DEFAULT NULL,
  `CYC_ZYWP` varchar(25) DEFAULT NULL,
  `CYC_SSCD` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b3_outerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b3_outerinfo`;
CREATE TABLE `b3_outerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(25) DEFAULT NULL,
  `LT_Z1` varchar(25) DEFAULT NULL,
  `LT_Z2` varchar(25) DEFAULT NULL,
  `LT_Z3` varchar(25) DEFAULT NULL,
  `LT_Y1` varchar(25) DEFAULT NULL,
  `LT_Y2` varchar(25) DEFAULT NULL,
  `LT_Y3` varchar(25) DEFAULT NULL,
  `LW_Z1` varchar(25) DEFAULT NULL,
  `LW_Z2` varchar(25) DEFAULT NULL,
  `LW_Z3` varchar(25) DEFAULT NULL,
  `LW_Y1` varchar(25) DEFAULT NULL,
  `LW_Y2` varchar(25) DEFAULT NULL,
  `LW_Y3` varchar(25) DEFAULT NULL,
  `CM_Z1` varchar(25) DEFAULT NULL,
  `CM_Y1` varchar(25) DEFAULT NULL,
  `CM_Y2` varchar(25) DEFAULT NULL,
  `CM_Y3` varchar(25) DEFAULT NULL,
  `CWB_Z1` varchar(25) DEFAULT NULL,
  `CWB_Z2` varchar(25) DEFAULT NULL,
  `CWB_Z3` varchar(25) DEFAULT NULL,
  `CWB_Y1` varchar(25) DEFAULT NULL,
  `CWB_Y2` varchar(25) DEFAULT NULL,
  `CWB_Y3` varchar(25) DEFAULT NULL,
  `CD_Z1` varchar(25) DEFAULT NULL,
  `CD_Z2` varchar(25) DEFAULT NULL,
  `CD_Y1` varchar(25) DEFAULT NULL,
  `CD_Y2` varchar(25) DEFAULT NULL,
  `HSJ_Z` varchar(25) DEFAULT NULL,
  `HSJ_Y` varchar(25) DEFAULT NULL,
  `CC_Z1` varchar(25) DEFAULT NULL,
  `CC_Z2` varchar(25) DEFAULT NULL,
  `CC_Z3` varchar(25) DEFAULT NULL,
  `CC_Z4` varchar(25) DEFAULT NULL,
  `CC_Z5` varchar(25) DEFAULT NULL,
  `CC_Z6` varchar(25) DEFAULT NULL,
  `CC_Y1` varchar(25) DEFAULT NULL,
  `CC_Y2` varchar(25) DEFAULT NULL,
  `CC_Y3` varchar(25) DEFAULT NULL,
  `CC_Y4` varchar(25) DEFAULT NULL,
  `CC_Y5` varchar(25) DEFAULT NULL,
  `CC_Y6` varchar(25) DEFAULT NULL,
  `BXG_QB` varchar(25) DEFAULT NULL,
  `BXG_HB` varchar(25) DEFAULT NULL,
  `FDBL_QB` varchar(25) DEFAULT NULL,
  `FDBL_HB` varchar(25) DEFAULT NULL,
  `YGQ_QB` varchar(25) DEFAULT NULL,
  `YGQ_HB` varchar(25) DEFAULT NULL,
  `DG` varchar(25) DEFAULT NULL,
  `DBKT` varchar(25) DEFAULT NULL,
  `DP` varchar(25) DEFAULT NULL,
  `PQG` varchar(25) DEFAULT NULL,
  `CHZHQ` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b4_innerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b4_innerinfo`;
CREATE TABLE `b4_innerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(25) DEFAULT NULL,
  `XDC_WZ` varchar(25) DEFAULT NULL,
  `XDC_DY` varchar(25) DEFAULT NULL,
  `XDC_SSCD` varchar(25) DEFAULT NULL,
  `DCC_DCCWZ` varchar(25) DEFAULT NULL,
  `DCC_KCDKWZ` varchar(25) DEFAULT NULL,
  `DCC_MCDKWZ` varchar(25) DEFAULT NULL,
  `DCC_CDQWZ` varchar(25) DEFAULT NULL,
  `DCC_WKCZ` varchar(25) DEFAULT NULL,
  `DCC_EDDY` varchar(25) DEFAULT NULL,
  `DCC_CZFS` varchar(25) DEFAULT NULL,
  `DCC_EDRL` varchar(25) DEFAULT NULL,
  `DCC_HDZT` varchar(25) DEFAULT NULL,
  `DCC_SSSCD` varchar(25) DEFAULT NULL,
  `DCC_XSSCD` varchar(25) DEFAULT NULL,
  `DCC_ZSSCD` varchar(25) DEFAULT NULL,
  `DCC_YSSCD` varchar(25) DEFAULT NULL,
  `DCC_QSSCD` varchar(25) DEFAULT NULL,
  `DCC_HSSCD` varchar(25) DEFAULT NULL,
  `DCC_DCLX` varchar(25) DEFAULT NULL,
  `DCC_DCXH` varchar(25) DEFAULT NULL,
  `DCC_DCEDRL` varchar(25) DEFAULT NULL,
  `DCC_DCEDDY` varchar(25) DEFAULT NULL,
  `DCGLXT_WZ` varchar(25) DEFAULT NULL,
  `DCGLXT_SSCD` varchar(25) DEFAULT NULL,
  `FDJC_DDJ` varchar(25) DEFAULT NULL,
  `FDJC_ZKB` varchar(25) DEFAULT NULL,
  `FDJC_DJKZQ` varchar(25) DEFAULT NULL,
  `FDJC_SRQ` varchar(25) DEFAULT NULL,
  `FDJC_JSX` varchar(25) DEFAULT NULL,
  `FDJC_LQFS` varchar(25) DEFAULT NULL,
  `FDJC_DYZHQ` varchar(25) DEFAULT NULL,
  `FDJC_ABS` varchar(25) DEFAULT NULL,
  `FDJC_PDH` varchar(25) DEFAULT NULL,
  `FDJC_ZQD` varchar(25) DEFAULT NULL,
  `FDJC_BXH` varchar(25) DEFAULT NULL,
  `FDJC_YQD` varchar(25) DEFAULT NULL,
  `FDJC_JQQG` varchar(25) DEFAULT NULL,
  `FDJC_FDdongJ` varchar(25) DEFAULT NULL,
  `FDJC_PQQG` varchar(25) DEFAULT NULL,
  `FDJC_QDJ` varchar(25) DEFAULT NULL,
  `FDJC_BSQ_LHQ` varchar(25) DEFAULT NULL,
  `FDJC_FDianJ` varchar(25) DEFAULT NULL,
  `JSS_YBB` varchar(25) DEFAULT NULL,
  `JSS_DYQ` varchar(25) DEFAULT NULL,
  `JSS_ZXP` varchar(25) DEFAULT NULL,
  `JSS_STX` varchar(25) DEFAULT NULL,
  `JSS_ZYJXH` varchar(25) DEFAULT NULL,
  `JSS_ZYFSX` varchar(25) DEFAULT NULL,
  `JSS_DHKG` varchar(25) DEFAULT NULL,
  `JSS_JSWZY` varchar(25) DEFAULT NULL,
  `JSS_BFQ` varchar(25) DEFAULT NULL,
  `JSS_FJSZY` varchar(25) DEFAULT NULL,
  `JSS_GFJ` varchar(25) DEFAULT NULL,
  `JSS_HPZY` varchar(25) DEFAULT NULL,
  `JSS_ZQM` varchar(25) DEFAULT NULL,
  `JSS_YQM` varchar(25) DEFAULT NULL,
  `JSS_ZHM` varchar(25) DEFAULT NULL,
  `JSS_YHM` varchar(25) DEFAULT NULL,
  `HBX_ZHCD` varchar(25) DEFAULT NULL,
  `HBX_YHCD` varchar(25) DEFAULT NULL,
  `HBX_ZYWP` varchar(25) DEFAULT NULL,
  `HBX_SSCD` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b4_outerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b4_outerinfo`;
CREATE TABLE `b4_outerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(255) DEFAULT NULL,
  `LT_ZQ` varchar(25) DEFAULT NULL,
  `LT_YQ` varchar(25) DEFAULT NULL,
  `LT_ZH` varchar(25) DEFAULT NULL,
  `LT_YH` varchar(25) DEFAULT NULL,
  `LW_ZQ` varchar(25) DEFAULT NULL,
  `LW_YQ` varchar(25) DEFAULT NULL,
  `LW_ZH` varchar(25) DEFAULT NULL,
  `LW_YH` varchar(25) DEFAULT NULL,
  `CM_ZQ` varchar(25) DEFAULT NULL,
  `CM_YQ` varchar(25) DEFAULT NULL,
  `CM_ZH` varchar(25) DEFAULT NULL,
  `CM_YH` varchar(25) DEFAULT NULL,
  `CC_ZQ` varchar(25) DEFAULT NULL,
  `CC_YQ` varchar(25) DEFAULT NULL,
  `CC_ZH` varchar(25) DEFAULT NULL,
  `CC_YH` varchar(25) DEFAULT NULL,
  `YZB_ZQ` varchar(25) DEFAULT NULL,
  `YZB_YQ` varchar(25) DEFAULT NULL,
  `YZB_ZH` varchar(25) DEFAULT NULL,
  `YZB_YH` varchar(25) DEFAULT NULL,
  `CD_ZQ` varchar(25) DEFAULT NULL,
  `CD_YQ` varchar(25) DEFAULT NULL,
  `CD_ZH` varchar(25) DEFAULT NULL,
  `CD_YH` varchar(25) DEFAULT NULL,
  `HSJ_ZQ` varchar(25) DEFAULT NULL,
  `HSJ_YQ` varchar(25) DEFAULT NULL,
  `BXG_QB` varchar(25) DEFAULT NULL,
  `BXG_HB` varchar(25) DEFAULT NULL,
  `FDBO_QB` varchar(25) DEFAULT NULL,
  `FDBL_HB` varchar(25) DEFAULT NULL,
  `YGQ_QB` varchar(25) DEFAULT NULL,
  `YGQ_HB` varchar(25) DEFAULT NULL,
  `JCG` varchar(25) DEFAULT NULL,
  `DG` varchar(25) DEFAULT NULL,
  `TC` varchar(25) DEFAULT NULL,
  `HBXG` varchar(25) DEFAULT NULL,
  `DP` varchar(25) DEFAULT NULL,
  `PQG` varchar(25) DEFAULT NULL,
  `CHZHQ` varchar(25) DEFAULT NULL,
  `WJCDXL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b5_innerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b5_innerinfo`;
CREATE TABLE `b5_innerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(25) DEFAULT NULL,
  `XDC_WZ` varchar(25) DEFAULT NULL,
  `XDC_DY` varchar(25) DEFAULT NULL,
  `XDC_SSCD` varchar(25) DEFAULT NULL,
  `DCC_DCCWZ` varchar(25) DEFAULT NULL,
  `DCC_CDKWZ` varchar(25) DEFAULT NULL,
  `DCC_CDQWZ` varchar(25) DEFAULT NULL,
  `DCC_WKCZ` varchar(25) DEFAULT NULL,
  `DCC_EDDY` varchar(25) DEFAULT NULL,
  `DCC_CZFS` varchar(25) DEFAULT NULL,
  `DCC_EDRL` varchar(25) DEFAULT NULL,
  `DCC_HDZT` varchar(25) DEFAULT NULL,
  `DCC_SSCD` varchar(25) DEFAULT NULL,
  `DCC_DCLX` varchar(25) DEFAULT NULL,
  `DCC_DCXH` varchar(25) DEFAULT NULL,
  `DCC_DCEDRL` varchar(25) DEFAULT NULL,
  `DCC_DCEDDY` varchar(25) DEFAULT NULL,
  `DCGLXT_WZ` varchar(25) DEFAULT NULL,
  `DCGLXT_SSCD` varchar(25) DEFAULT NULL,
  `FDJC_DDJ` varchar(25) DEFAULT NULL,
  `FDJC_ZKB` varchar(25) DEFAULT NULL,
  `FDJC_DJKZQ` varchar(25) DEFAULT NULL,
  `FDJC_SRQ` varchar(25) DEFAULT NULL,
  `FDJC_JSX` varchar(25) DEFAULT NULL,
  `FDJC_LQFS` varchar(25) DEFAULT NULL,
  `FDJC_DYZHQ` varchar(25) DEFAULT NULL,
  `FDJC_ABS` varchar(25) DEFAULT NULL,
  `FDJC_PDH` varchar(25) DEFAULT NULL,
  `FDJC_ZQD` varchar(25) DEFAULT NULL,
  `FDJC_BXH` varchar(25) DEFAULT NULL,
  `FDJC_YQD` varchar(25) DEFAULT NULL,
  `FDJC_JQQG` varchar(25) DEFAULT NULL,
  `FDJC_FDdongJ` varchar(25) DEFAULT NULL,
  `FDJC_PQQG` varchar(25) DEFAULT NULL,
  `FDJC_QDJ` varchar(25) DEFAULT NULL,
  `FDJC_BSQ_LHQ` varchar(25) DEFAULT NULL,
  `FDJC_FDianJ` varchar(25) DEFAULT NULL,
  `CYC_YBB` varchar(25) DEFAULT NULL,
  `CYC_BFQ` varchar(25) DEFAULT NULL,
  `CYC_JXH` varchar(25) DEFAULT NULL,
  `CYC_JSQ` varchar(25) DEFAULT NULL,
  `CYC_ZXP` varchar(25) DEFAULT NULL,
  `CYC_JSWZQ` varchar(25) DEFAULT NULL,
  `CYC_DHKG` varchar(25) DEFAULT NULL,
  `CYC_FJSZY` varchar(25) DEFAULT NULL,
  `CYC_GFJ` varchar(25) DEFAULT NULL,
  `CYC_CKZQ` varchar(25) DEFAULT NULL,
  `CYC_QBDB` varchar(25) DEFAULT NULL,
  `CYC_HBDB` varchar(25) DEFAULT NULL,
  `CYC_ZQCD` varchar(25) DEFAULT NULL,
  `CYC_YQCD` varchar(25) DEFAULT NULL,
  `CYC_ZHCD` varchar(25) DEFAULT NULL,
  `CYC_YHCD` varchar(25) DEFAULT NULL,
  `CYC_CMZ1` varchar(25) DEFAULT NULL,
  `CYC_CMY1` varchar(25) DEFAULT NULL,
  `CYC_CMY2` varchar(25) DEFAULT NULL,
  `CYC_CMY3` varchar(25) DEFAULT NULL,
  `CYC_ZYWP` varchar(25) DEFAULT NULL,
  `CYC_SSCD` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b5_outerinfo
-- ----------------------------
DROP TABLE IF EXISTS `b5_outerinfo`;
CREATE TABLE `b5_outerinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Acc_ID` int(11) DEFAULT NULL,
  `VIN` varchar(25) DEFAULT NULL,
  `LT_Z1` varchar(25) DEFAULT NULL,
  `LT_Z2` varchar(25) DEFAULT NULL,
  `LT_Z3` varchar(25) DEFAULT NULL,
  `LT_Y1` varchar(25) DEFAULT NULL,
  `LT_Y2` varchar(25) DEFAULT NULL,
  `LT_Y3` varchar(25) DEFAULT NULL,
  `LW_Z1` varchar(25) DEFAULT NULL,
  `LW_Z2` varchar(25) DEFAULT NULL,
  `LW_Z3` varchar(25) DEFAULT NULL,
  `LW_Y1` varchar(25) DEFAULT NULL,
  `LW_Y2` varchar(25) DEFAULT NULL,
  `LW_Y3` varchar(25) DEFAULT NULL,
  `CM_Z1` varchar(25) DEFAULT NULL,
  `CM_Y1` varchar(25) DEFAULT NULL,
  `CM_Y2` varchar(25) DEFAULT NULL,
  `CM_Y3` varchar(25) DEFAULT NULL,
  `CWB_Z1` varchar(25) DEFAULT NULL,
  `CWB_Z2` varchar(25) DEFAULT NULL,
  `CWB_Z3` varchar(25) DEFAULT NULL,
  `CWB_Y1` varchar(25) DEFAULT NULL,
  `CWB_Y2` varchar(25) DEFAULT NULL,
  `CWB_Y3` varchar(25) DEFAULT NULL,
  `CD_Z1` varchar(25) DEFAULT NULL,
  `CD_Z2` varchar(25) DEFAULT NULL,
  `CD_Y1` varchar(25) DEFAULT NULL,
  `CD_Y2` varchar(25) DEFAULT NULL,
  `HSJ_Z` varchar(25) DEFAULT NULL,
  `HSJ_Y` varchar(25) DEFAULT NULL,
  `CC_Z1` varchar(25) DEFAULT NULL,
  `CC_Z2` varchar(25) DEFAULT NULL,
  `CC_Z3` varchar(25) DEFAULT NULL,
  `CC_Z4` varchar(25) DEFAULT NULL,
  `CC_Z5` varchar(25) DEFAULT NULL,
  `CC_Z6` varchar(25) DEFAULT NULL,
  `CC_Y1` varchar(25) DEFAULT NULL,
  `CC_Y2` varchar(25) DEFAULT NULL,
  `CC_Y3` varchar(25) DEFAULT NULL,
  `CC_Y4` varchar(25) DEFAULT NULL,
  `CC_Y5` varchar(25) DEFAULT NULL,
  `CC_Y6` varchar(25) DEFAULT NULL,
  `BXG_QB` varchar(25) DEFAULT NULL,
  `BXG_HB` varchar(25) DEFAULT NULL,
  `FDBL_QB` varchar(25) DEFAULT NULL,
  `FDBL_HB` varchar(25) DEFAULT NULL,
  `YGQ_QB` varchar(25) DEFAULT NULL,
  `YGQ_HB` varchar(25) DEFAULT NULL,
  `DG` varchar(25) DEFAULT NULL,
  `DBKT` varchar(25) DEFAULT NULL,
  `DP` varchar(25) DEFAULT NULL,
  `PQG` varchar(25) DEFAULT NULL,
  `CHZHQ` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=20332 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b_carinfo
-- ----------------------------
DROP TABLE IF EXISTS `b_carinfo`;
CREATE TABLE `b_carinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `VIN` varchar(50) DEFAULT NULL,
  `Acc_ID` int(11) DEFAULT NULL,
  `Brand` varchar(50) DEFAULT NULL,
  `Register_Time` datetime DEFAULT NULL,
  `Car_Property` varchar(50) DEFAULT NULL,
  `Car_Miles` varchar(20) DEFAULT NULL,
  `Befo_RunDis` varchar(20) DEFAULT NULL,
  `Befo_RunTime` varchar(20) DEFAULT NULL,
  `Befo_StopTime` varchar(20) DEFAULT NULL,
  `State` varchar(20) DEFAULT NULL,
  `AftLoc` varchar(20) DEFAULT NULL,
  `Trans_Method` varchar(20) DEFAULT NULL,
  `If_Modify` varchar(20) DEFAULT NULL,
  `Modify_Time` datetime DEFAULT NULL,
  `Modify_Part` varchar(100) DEFAULT NULL,
  `Modify_Pos` varchar(100) DEFAULT NULL,
  `Maintain_Time` datetime DEFAULT NULL,
  `Maintain_Purpose` varchar(50) DEFAULT NULL,
  `Maintain_Content` varchar(100) DEFAULT NULL,
  `Insurance` varchar(20) DEFAULT NULL,
  `Insurance_Time` datetime DEFAULT NULL,
  `Insurance_Type` varchar(20) DEFAULT NULL,
  `MYQS` varchar(20) DEFAULT NULL,
  `QHBW` varchar(100) DEFAULT NULL,
  `Car_Type` int(11) NOT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=177 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b_envburninfo
-- ----------------------------
DROP TABLE IF EXISTS `b_envburninfo`;
CREATE TABLE `b_envburninfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `VIN` varchar(255) DEFAULT NULL,
  `Acc_ID` int(11) DEFAULT NULL,
  `Front1` varchar(20) DEFAULT NULL COMMENT '前方主要物体',
  `Front1_Burn` varchar(20) DEFAULT NULL COMMENT '前方主要物体烧损程度',
  `Left1` varchar(20) DEFAULT NULL,
  `Left1_Burn` varchar(20) DEFAULT NULL,
  `Right1` varchar(20) DEFAULT NULL,
  `Right1_Burn` varchar(20) DEFAULT NULL,
  `Up1` varchar(20) DEFAULT NULL,
  `Up1_Burn` varchar(20) DEFAULT NULL,
  `Down1` varchar(20) DEFAULT NULL,
  `Down1_Burn` varchar(20) DEFAULT NULL,
  `Front2` varchar(20) DEFAULT NULL,
  `Front2_Burn` varchar(20) DEFAULT NULL,
  `Left2` varchar(20) DEFAULT NULL,
  `Left2_Burn` varchar(20) DEFAULT NULL,
  `Right2` varchar(20) DEFAULT NULL,
  `Right2_Burn` varchar(20) DEFAULT NULL,
  `Up2` varchar(20) DEFAULT NULL,
  `Up2_Burn` varchar(20) DEFAULT NULL,
  `Down2` varchar(20) DEFAULT NULL,
  `Down2_Burn` varchar(20) DEFAULT '',
  `Back1` varchar(25) DEFAULT NULL,
  `Back1_Burn` varchar(25) DEFAULT NULL,
  `Back2` varchar(25) DEFAULT NULL,
  `Back2_Burn` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1255 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for b_firelocinfo
-- ----------------------------
DROP TABLE IF EXISTS `b_firelocinfo`;
CREATE TABLE `b_firelocinfo` (
  `Car_Id` int(11) NOT NULL AUTO_INCREMENT,
  `VIN` varchar(255) DEFAULT NULL,
  `Acc_ID` int(11) DEFAULT NULL,
  `Main_BurnUnit1` varchar(30) DEFAULT NULL COMMENT '主要 烧损部件',
  `Main_BurnUnit1_Degree` varchar(30) DEFAULT NULL,
  `Unit1_Circurt` varchar(30) DEFAULT NULL COMMENT '部件自身电气线路烧损情况',
  `Other1_Circurt` varchar(30) DEFAULT NULL COMMENT '部件附近电路烧损情况',
  `Main_BurnUnit2` varchar(30) DEFAULT NULL,
  `Main_BurnUnit2_Degree` varchar(30) DEFAULT NULL,
  `Unit2_Circurt` varchar(30) DEFAULT NULL,
  `Other2_Circurt` varchar(30) DEFAULT NULL,
  `Main_BurnObject1_Name` varchar(30) DEFAULT NULL,
  `Main_BurnObject1_Burn` varchar(30) DEFAULT NULL,
  `Main_BurnObject2_Name` varchar(30) DEFAULT NULL,
  `Main_BurnObject2_Burn` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`Car_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for c_peopleinfo
-- ----------------------------
DROP TABLE IF EXISTS `c_peopleinfo`;
CREATE TABLE `c_peopleinfo` (
  `People_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '人员Id',
  `Acc_ID` int(11) DEFAULT NULL,
  `People_Type` varchar(20) DEFAULT NULL COMMENT '人员类型',
  `People_Sex` varchar(10) DEFAULT NULL COMMENT '人员性别',
  `People_Age` int(11) DEFAULT NULL COMMENT '年龄',
  `Invest_Loc` varchar(20) DEFAULT NULL COMMENT '调查地点',
  `Invest_Method` varchar(20) DEFAULT NULL COMMENT '调查方式',
  `If_Smoke` varchar(10) DEFAULT NULL COMMENT '是否抽烟',
  `If_Drink` varchar(10) DEFAULT NULL COMMENT '是否饮酒',
  `If_Injury` varchar(10) DEFAULT NULL COMMENT '伤情',
  `Injury_Loc` varchar(20) DEFAULT NULL COMMENT '受伤部位',
  `Car_Perform` varchar(20) DEFAULT NULL COMMENT '车辆性能',
  `Measure1` varchar(20) DEFAULT NULL COMMENT '异常现象采取措施 ',
  `Fire_Find_Loc` varchar(20) DEFAULT NULL COMMENT '发现时人员所在位置',
  `Distance` double(11,0) DEFAULT NULL COMMENT '相距距离',
  `Phenomenon` varchar(50) DEFAULT NULL COMMENT '表明起火的主要现象',
  `Measure2` varchar(50) DEFAULT NULL COMMENT '初期火灾采取措施',
  `Fire_Loc` varchar(50) DEFAULT NULL COMMENT '火焰位置',
  `Fire_Height` varchar(20) DEFAULT NULL COMMENT '火焰高度 ',
  `Fire_HeightAll` double(11,0) DEFAULT NULL COMMENT '火焰整体高度',
  `Fog_Loc` varchar(50) DEFAULT NULL COMMENT '烟气位置',
  `Fog_Color` varchar(10) DEFAULT NULL COMMENT '烟气颜色',
  `Fog_Height` varchar(10) DEFAULT NULL COMMENT '烟气高度',
  `Fog_HeightAll` double(11,0) DEFAULT NULL COMMENT '烟气整体高度',
  PRIMARY KEY (`People_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2110174344 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for image
-- ----------------------------
DROP TABLE IF EXISTS `image`;
CREATE TABLE `image` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(50) NOT NULL,
  `src` varchar(100) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=571 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for picture
-- ----------------------------
DROP TABLE IF EXISTS `picture`;
CREATE TABLE `picture` (
  `pid` int(11) NOT NULL AUTO_INCREMENT,
  `ano` varchar(30) NOT NULL,
  `pname` varchar(50) NOT NULL,
  `path` varchar(255) NOT NULL,
  `ptype` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(20) NOT NULL,
  `username` varchar(10) NOT NULL,
  `password` varchar(20) NOT NULL,
  `mail` varchar(25) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `Register_Time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
